### ISSUE TITLE
Add ability to set a NodePort port number

### ISSUE THREAD

**Issue by mossroy** [sj14/helm-charts#3]
The Helm chart currently allows to choose a Service type (ClusterIP by default).

However, if I choose a NodePort type, I found no way to set the corresponding high port: it's generated by k8s where I would like to set it.

**Comment by sj14** [comment]
Right, I've added `service.nodePort` in the values file. Please check again with v0.1.5.

**Comment by mossroy** [comment]
Wow, that was fast, many thanks!
I've tested with v0.1.5 and it works fine: I can now set the nodePort port number in the values.yaml of my Helm release.
