### ISSUE TITLE
What is the purpose of the Ingress in this Helm Chart?

### ISSUE THREAD

**Issue by mossroy** [sj14/helm-charts#4]
Maybe I missed something but I don't get the purpose of the optional Ingress in this Helm chart.

An Ingress can only handle HTTP/HTTPS protocol, while the underlying service exposes the SSH/SFTP protocol.

Is it possible to access the server with an SFTP client through an Ingress?

**Comment by sj14** [comment]
Thanks for the feedback. No, I think you are right. I didn't think about it and left it when it was added with `helm create`.
